#!/bin/bash

read -p "IP_ADDRESS:" IP_ADDRESS
read -p "ROOT_PASSWORD:" ROOT_PASSWORD

if [[ "$PUBLIC_KEY" = "" ]]; then
  read -p "PUBLIC_KEY_PATH: " PUBLIC_KEY_PATH
  if [[ "$PUBLIC_KEY_PATH" == "" ]]; then
    PUBLIC_KEY_PATH=$HOME/.ssh/id_rsa.pub
  fi
  PUBLIC_KEY=$(cat $PUBLIC_KEY_PATH)
fi

sshpass -p "$ROOT_PASSWORD" ssh -tt root@$IP_ADDRESS << EOF
  mkdir .ssh
  echo $PUBLIC_KEY > .ssh/authorized_keys
  chmod 0600 .ssh/authorized_keys
  yes | apt-get install python
  exit
EOF
