#!/bin/bash -xe

echo "Install ansible"

for PKG in "ansible openssh sshpass" ; do
  apt-get install $PKG \
  || yum install $PKG \
  || brew install $PKG \
  || pacman -S $PKG \
  || brew install $PKG \
  || choco install $PKG
done
