Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  # TODO name the vagrant machine
  # config.vm.define = "ansible-test"
  config.vm.network "private_network", ip: "192.168.123.124"
  # config.ssh.username = 'root'
  # config.ssh.password = 'vagrant'
end
